# Google Trends, HCUP, & U.S. Census Bureau Data Collection
**Author:** J. Casey Brookshier  
**Date:** July 15, 2026

## Objective

Collect, clean, and merge Google Trends, HCUP, and U.S. Census Bureau data to build a state-year dataset for predicting future inpatient psychiatric admissions.

### Data Sources
**Google Trends:** State-level suicide/crisis search interest (predictors)
  **HCUP:** Annual Mental Health/Substance Use inpatient admissions (outcome)
  **U.S. Census Bureau:** State population estimates (normalization)

### Workflow
**Collect → Clean → Merge → Model → Evaluate**

The resulting dataset supports regression, Random Forest, XGBoost, PCA, hierarchical clustering, and SHAP feature importance analyses.

In [2]:
import os

print(os.getcwd())
print(os.path.exists(
    "/Users/caseybrookshier/Desktop/Data Science job attainment planning/DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"
))

/Users/caseybrookshier
True

In [ ]:
# !pip install urllib3==1.26.18
# !pip install pyreadr
# !pip install pyreadstat

In [ ]:
"""
Google Trends Data Collection for Team Rho Capstone Project

Purpose:
Create state-year Google Trends predictors (2013-2023) for forecasting
future state-level suicide related inpatient psychiatric admissions.

"""

from pytrends.request import TrendReq
import pandas as pd
import time
import os
import random


# connect w/ google trends API, collect predictor search data

pytrends = TrendReq(
    hl="en-US",
    tz=360
)

# search terms/predictors

SEARCH_TERMS = [
    "suicidal thoughts",
    "suicide hotline",
    "self harm",
    "mental health crisis",
    "suicide prevention",
    "crisis hotline",
    "psychiatric hospital",
    "depression help"
]


# states

STATES = {
    "AL":"Alabama",
    "AK":"Alaska",
    "AZ":"Arizona",
    "AR":"Arkansas",
    "CA":"California",
    "CO":"Colorado",
    "CT":"Connecticut",
    "DE":"Delaware",
    "FL":"Florida",
    "GA":"Georgia",
    "HI":"Hawaii",
    "ID":"Idaho",
    "IL":"Illinois",
    "IN":"Indiana",
    "IA":"Iowa",
    "KS":"Kansas",
    "KY":"Kentucky",
    "LA":"Louisiana",
    "ME":"Maine",
    "MD":"Maryland",
    "MA":"Massachusetts",
    "MI":"Michigan",
    "MN":"Minnesota",
    "MS":"Mississippi",
    "MO":"Missouri",
    "MT":"Montana",
    "NE":"Nebraska",
    "NV":"Nevada",
    "NH":"New Hampshire",
    "NJ":"New Jersey",
    "NM":"New Mexico",
    "NY":"New York",
    "NC":"North Carolina",
    "ND":"North Dakota",
    "OH":"Ohio",
    "OK":"Oklahoma",
    "OR":"Oregon",
    "PA":"Pennsylvania",
    "RI":"Rhode Island",
    "SC":"South Carolina",
    "SD":"South Dakota",
    "TN":"Tennessee",
    "TX":"Texas",
    "UT":"Utah",
    "VT":"Vermont",
    "VA":"Virginia",
    "WA":"Washington",
    "WV":"West Virginia",
    "WI":"Wisconsin",
    "WY":"Wyoming",
    "DC":"District of Columbia"
}


# create files

RAW_FILE = "google_trends_raw_progress.csv"

FINAL_FILE = "google_trends_state_year_2013_2023.csv"

FAILED_FILE = "google_trends_failed_queries.csv"


TIMEFRAME = "2013-01-01 2023-12-31"

MAX_RETRIES = 5


# load google trends data

if os.path.exists(RAW_FILE):

    raw = pd.read_csv(RAW_FILE)

    records = [raw]

    completed = set(
        zip(
            raw["State"],
            raw["Search_Term"]
        )
    )

else:

    records = []

    completed = set()


failed_queries = []


# collect google trends data, handle API fail

def get_google_trends(term, geo):

    for attempt in range(MAX_RETRIES):

        try:

            pytrends.build_payload(
                kw_list=[term],
                timeframe=TIMEFRAME,
                geo=geo
            )

            data = pytrends.interest_over_time()

            if not data.empty:

                return data


        except Exception as e:

            wait = 10 * (2 ** attempt)

            print(
                f"Retry {attempt+1}/{MAX_RETRIES}; waiting {wait}s"
            )

            time.sleep(wait)


    return None



# download predictor data

for state_abbrev, state_name in STATES.items():

    geo = f"US-{state_abbrev}"

    print(
        f"\nProcessing {state_name}"
    )


    for term in SEARCH_TERMS:


        if (state_name, term) in completed:

            print(
                f"Skipping {state_name} - {term}"
            )

            continue


        trends = get_google_trends(
            term,
            geo
        )


        if trends is None:

            failed_queries.append(
                {
                    "State": state_name,
                    "Term": term
                }
            )

            continue


        trends = trends.reset_index()

        trends["Year"] = (
            trends["date"]
            .dt.year
        )


        annual = (
            trends
            .groupby("Year")[term]
            .mean()
            .reset_index()
        )


        annual["State"] = state_name

        annual["Search_Term"] = term


        records.append(
            annual
        )


        # Save checkpoint immediately
        checkpoint = pd.concat(
            records,
            ignore_index=True
        )


        checkpoint.to_csv(
            RAW_FILE,
            index=False
        )


        time.sleep(
            random.uniform(5,10)
        )


# convert long-format data into one row per state-year

raw = pd.concat(
    records,
    ignore_index=True
)


panel = (
    raw
    .pivot_table(
        index=[
            "State",
            "Year"
        ],
        columns="Search_Term",
        values=raw.columns[1],
        aggfunc="mean"
    )
    .reset_index()
)


panel.columns = [
    str(c)
    .replace(" ","_")
    .replace("-","_")
    .lower()
    for c in panel.columns
]


# create one year timelag variables to test hypothesis

panel = panel.sort_values(
    [
        "state",
        "year"
    ]
)


predictors = [
    c for c in panel.columns
    if c not in [
        "state",
        "year"
    ]
]


for col in predictors:

    panel[col + "_lag1"] = (
        panel
        .groupby("state")[col]
        .shift(1)
    )


# save data set

panel.to_csv(
    FINAL_FILE,
    index=False
)


if failed_queries:

    pd.DataFrame(
        failed_queries
    ).to_csv(
        FAILED_FILE,
        index=False
    )


print("COMPLETE")
print(panel.head())

In [ ]:
# Copy files to project folder
import os
import shutil

# files created by Google Trends notebook


files_to_copy = [
    "google_trends_raw_progress.csv",
    "google_trends_state_year_2013_2023.csv",
    "google_trends_failed_queries.csv"
]


# send to destination

destination = r"/Users/caseybrookshier/Desktop/Data Science job attainment planning/DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"


# create destination if it does not exist

os.makedirs(
    destination,
    exist_ok=True
)


# copy files to project folder

for file in files_to_copy:

    if os.path.exists(file):

        shutil.copy(
            file,
            destination
        )

        print(
            f"Copied: {file}"
        )

    else:

        print(
            f"Not found (skipped): {file}"
        )


print("\nCSV transfer complete.")

In [ ]:
#data set head/dimensions
import pandas as pd

# load raw Google Trends progress file
raw_trends = pd.read_csv(
    "google_trends_raw_progress.csv"
)

raw_trends.head()

print("Shape:", raw_trends.shape)

print("\nColumns:")
print(raw_trends.columns.tolist())

raw_trends.head()

In [ ]:
# build State Population Dataset (2013-2023), use following
#   nst-est2020.xlsx
#   NST-EST2025-POP.xlsx


import pandas as pd
from pathlib import Path

# file locations

DATA_DIR = Path("/Users/caseybrookshier/Desktop/Data Science job attainment planning/DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw")

OLD_FILE = DATA_DIR / "nst-est2020.xlsx"
NEW_FILE = DATA_DIR / "NST-EST2025-POP.xlsx"

OUTPUT_FILE = DATA_DIR / "uscb_state_population_2013_2023.csv"


# read worksheet

old_raw = pd.read_excel(OLD_FILE, header=None)
new_raw = pd.read_excel(NEW_FILE, header=None)

# locate first state (.Alabama)


old_start = old_raw[old_raw.iloc[:,0].astype(str).str.startswith(".Alabama")].index[0]
new_start = new_raw[new_raw.iloc[:,0].astype(str).str.startswith(".Alabama")].index[0]



# build OLD (2013-2020) state pop.


old_years = [
    "State","2010","Base","2010","2011","2012",
    "2013","2014","2015","2016","2017",
    "2018","2019","2020_Apr","2020"
]

old = old_raw.iloc[old_start:].copy()
old.columns = old_years

old = old[
    ["State","2013","2014","2015","2016",
     "2017","2018","2019","2020"]
]

# build NEW (2021-2023)

new_years = [
    "State","Base","2020","2021",
    "2022","2023","2024","2025"
]

new = new_raw.iloc[new_start:].copy()
new.columns = new_years

new = new[
    ["State","2021","2022","2023"]
]

# merge

wide = old.merge(new,on="State",how="left")

# remove leading dots from state names
wide["State"] = (
    wide["State"]
    .astype(str)
    .str.replace(".","",regex=False)
    .str.strip()
)

# keep only states + DC
exclude = {
    "United States",
    "Northeast",
    "Midwest",
    "South",
    "West",
    "Puerto Rico"
}

wide = wide[~wide["State"].isin(exclude)]

# convert to long format

population = wide.melt(
    id_vars="State",
    var_name="Year",
    value_name="state_population"
)

population["Year"] = population["Year"].astype(int)
population["state_population"] = (
    pd.to_numeric(population["state_population"], errors="coerce")
    .astype("Int64")
)

population = (
    population
    .sort_values(["State","Year"])
    .reset_index(drop=True)
)

population.to_csv(OUTPUT_FILE,index=False)

print("Saved:", OUTPUT_FILE)
print("Rows:", len(population))
print(population.head(20))

In [ ]:
# inspect structure of HCUP data tab

import pandas as pd
from pathlib import Path

RAW = Path(
    "/Users/caseybrookshier/Desktop/Data Science job attainment planning/"
    "DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"
)

HCUP_FILE = RAW / "DownloadTable_StatePayerIP_2026-03-20.xls"

# read the actual data worksheet
df = pd.read_excel(HCUP_FILE, sheet_name="Data")

print(df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 25 rows:")
print(df.head(25))

print("\nData types:")
print(df.dtypes)

In [10]:

# HCUP MENTAL HEALTH ADMISSIONS CLEANING PIPELINE
# Input:DownloadTable_StatePayerIP_2026-03-20.xls
# Output:hcup_state_year_mental_health_admissions_2013_2023.csv
#   create accurate State x Year mental health inpatient
#   admissions table for predictive modeling.


import pandas as pd
import numpy as np
from pathlib import Path

# paths


RAW = Path(
    "/Users/caseybrookshier/Desktop/Data Science job attainment planning/"
    "DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"
)


HCUP_FILE = RAW / "DownloadTable_StatePayerIP_2026-03-20.xls"


OUTPUT = RAW / (
    "hcup_state_year_mental_health_admissions_2013_2023.csv"
)

# load HCUP raw sheet


raw = pd.read_excel(
    HCUP_FILE,
    sheet_name="Data",
    header=None
)


print("Raw HCUP shape:")
print(raw.shape)

# find header row

header_row = None


for i in range(len(raw)):

    row = raw.iloc[i].astype(str).tolist()

    if (
        "State" in row
        and "Hospitalization Type" in row
        and "Expected Payer" in row
    ):
        header_row = i
        break



if header_row is None:
    raise ValueError(
        "HCUP header row not found."
    )


print("\nUsing header row:")
print(header_row)

# reload with correct header

hcup = pd.read_excel(
    HCUP_FILE,
    sheet_name="Data",
    header=header_row
)

hcup.columns = (
    hcup.columns
    .astype(str)
    .str.strip()
)

# identify quarterly columns

quarter_cols = [
    c for c in hcup.columns
    if (
        isinstance(c, str)
        and len(c) >= 7
        and c[:4].isdigit()
        and "Q" in c
    )
]


print("\nQuarter columns detected:")
print(len(quarter_cols))

# numeric conversion

for c in quarter_cols:

    hcup[c] = (
        hcup[c]
        .astype(str)
        .str.replace(",", "", regex=False)
        .replace(
            ["nan", "None", ""],
            np.nan
        )
    )


    hcup[c] = pd.to_numeric(
        hcup[c],
        errors="coerce"
    )

# keep 2013-2023 only

analysis_quarters = [
    c for c in quarter_cols
    if any(
        str(y) in c
        for y in range(2013,2024)
    )
]


hcup = hcup[
    [
        "State",
        "Hospitalization Type",
        "Expected Payer"
    ]
    +
    analysis_quarters
]

# mental health only

mh = hcup[
    hcup["Hospitalization Type"]
    ==
    "Mental Health/Substance Use"
].copy()



print("\nMental health rows:")
print(mh.shape)

# remove HCUP calculated rows


summary_patterns = (
    "Combined|"
    "Sum|"
    "All expected"
)


mh = mh[
    ~mh["Expected Payer"]
    .str.contains(
        summary_patterns,
        case=False,
        regex=True,
        na=False
    )
]

# keep only independent payer groups


valid_payers = [
    "Medicare, age 65+",
    "Medicaid, age 19-64",
    "Private, age 19-64",
    "Self-Pay/No Charge, age 19-64"
]


mh = mh[
    mh["Expected Payer"]
    .isin(valid_payers)
]



print("\nRemaining payer categories:")
print(
    mh["Expected Payer"]
    .unique()
)



print("\nRows after payer filtering:")
print(mh.shape)

# aggregate payer categories

mh_state_quarter = (
    mh
    .groupby("State")[analysis_quarters]
    .sum(min_count=1)
    .reset_index()
)

# quarterly -> Annual


annual_records = []


for year in range(2013,2024):


    cols = [
        c for c in analysis_quarters
        if str(year) in c
    ]


    temp = mh_state_quarter[
        ["State"] + cols
    ].copy()



    temp["Year"] = year



    temp[
        "mental_health_admissions"
    ] = (
        temp[cols]
        .sum(
            axis=1,
            min_count=1
        )
    )



    annual_records.append(
        temp[
            [
                "State",
                "Year",
                "mental_health_admissions"
            ]
        ]
    )



hcup_clean = pd.concat(
    annual_records,
    ignore_index=True
)

# remove impossible outputs

hcup_clean = hcup_clean[
    hcup_clean["mental_health_admissions"]
    >= 0
]

# validation

print("\n==============================")
print("FINAL VALIDATION")
print("==============================")


print("\nShape:")
print(
    hcup_clean.shape
)


print("\nStates:")
print(
    hcup_clean["State"]
    .nunique()
)


print("\nYears:")
print(
    sorted(
        hcup_clean["Year"]
        .unique()
    )
)



print("\nDuplicate State-Year rows:")
print(
    hcup_clean
    .duplicated(
        ["State","Year"]
    )
    .sum()
)



print("\nAdmission distribution:")
print(
    hcup_clean[
        "mental_health_admissions"
    ]
    .describe()
)



print("\nTop state-year values:")
print(
    hcup_clean
    .sort_values(
        "mental_health_admissions",
        ascending=False
    )
    .head(15)
)

# notebook display

display(
    hcup_clean
    .sort_values(
        ["State","Year"]
    )
    .head(50)
)

#save

hcup_clean.to_csv(
    OUTPUT,
    index=False
)


print("\nSaved:")
print(OUTPUT)

Raw HCUP shape:
(1936, 94)

Using header row:
3

Quarter columns detected:
91

Mental health rows:
(322, 47)

Remaining payer categories:
['Medicare, age 65+' 'Medicaid, age 19-64' 'Private, age 19-64'
 'Self-Pay/No Charge, age 19-64']

Rows after payer filtering:
(184, 47)

==============================
FINAL VALIDATION
==============================

Shape:
(496, 3)

States:
46

Years:
[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

Duplicate State-Year rows:
0

Admission distribution:
count       496.000000
mean      27206.250000
std       29563.800402
min        1150.000000
25%        8287.500000
50%       16175.000000
75%       33712.500000
max      145100.000000
Name: mental_health_admissions, dtype: float64

Top state-year values:
          State  Year  mental_health_admissions
73     New York  2014                  145100.0
119    New York  2015                  144950.0
27     New York  2013                  144900.0
257    New York  2018                  141700.0
303    New York  2019                  139350.0
211    New York  2017                  139200.0
165    New York  2016                  137600.0
49   California  2014                  124900.0
95   California  2015                  121600.0
233  California  2018                  121450.0
3    California  2013                  120850.0
349    New York  2020                  120000.0
279  California  2019                  118350.0
187  California  2017                  116000.0
487    New York  2023                  114550.0

          State  Year  mental_health_admissions
92       Alaska  2015                    2200.0
138      Alaska  2016                    2150.0
184      Alaska  2017                    2250.0
230      Alaska  2018                    2350.0
276      Alaska  2019                    2450.0
322      Alaska  2020                    2550.0
368      Alaska  2021                    2800.0
414      Alaska  2022                    2900.0
460      Alaska  2023                    2750.0
1       Arizona  2013                   16150.0
47      Arizona  2014                   15050.0
93      Arizona  2015                   14300.0
139     Arizona  2016                   14300.0
185     Arizona  2017                   13850.0
231     Arizona  2018                   17500.0
277     Arizona  2019                   16050.0
323     Arizona  2020                   16200.0
369     Arizona  2021                   15950.0
415     Arizona  2022                   12100.0
461     Arizona  2023                   20450.0
2      Arkansas  2013                   14450.0
48     Arkansas  2014                   15300.0
94     Arkansas  2015                   16050.0
140    Arkansas  2016                   14700.0
186    Arkansas  2017                   14700.0
232    Arkansas  2018                   16000.0
278    Arkansas  2019                   17850.0
324    Arkansas  2020                   17700.0
370    Arkansas  2021                   17750.0
416    Arkansas  2022                   17950.0
462    Arkansas  2023                   18800.0
3    California  2013                  120850.0
49   California  2014                  124900.0
95   California  2015                  121600.0
141  California  2016                  113750.0
187  California  2017                  116000.0
233  California  2018                  121450.0
279  California  2019                  118350.0
325  California  2020                  106600.0
371  California  2021                  109900.0
417  California  2022                  108450.0
4      Colorado  2013                   14200.0
50     Colorado  2014                   14350.0
96     Colorado  2015                   14150.0
142    Colorado  2016                   13100.0
188    Colorado  2017                   13600.0
234    Colorado  2018                   14450.0
280    Colorado  2019                   14350.0
326    Colorado  2020                   14300.0
372    Colorado  2021                   14050.0

Saved:
/Users/caseybrookshier/Desktop/Data Science job attainment planning/DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw/hcup_state_year_mental_health_admissions_2013_2023.csv

In [12]:

# HCUP ACCURACY AUDIT
# Verify that the cleaned mental health admissions table
#   exactly matches the original HCUP spreadsheet.


import pandas as pd

print("=" * 60)
print("HCUP ACCURACY AUDIT")
print("=" * 60)

# dataset summary


print("\n1. CLEAN DATASET SUMMARY")
print("-" * 60)

print(f"Rows: {len(hcup_clean)}")
print(f"States: {hcup_clean['State'].nunique()}")
print(f"Years: {sorted(hcup_clean['Year'].unique())}")


# duplicate check

print("\n2. DUPLICATE STATE-YEAR CHECK")
print("-" * 60)

duplicates = hcup_clean.duplicated(
    subset=["State", "Year"]
).sum()

print(f"Duplicate State-Year rows: {duplicates}")

# missing State-Year combinations


print("\n3. MISSING STATE-YEAR COMBINATIONS")
print("-" * 60)

expected = pd.MultiIndex.from_product(
    [
        sorted(hcup_clean["State"].unique()),
        range(2013, 2024)
    ],
    names=["State", "Year"]
).to_frame(index=False)

missing = (
    expected
    .merge(
        hcup_clean,
        on=["State", "Year"],
        how="left",
        indicator=True
    )
)

missing = missing[
    missing["_merge"] == "left_only"
][["State", "Year"]]

print(f"Missing combinations: {len(missing)}")

if len(missing):
    print(missing)

# missing values

print("\n4. MISSING VALUES")
print("-" * 60)

print(hcup_clean.isna().sum())

# negative values

print("\n5. NEGATIVE ADMISSIONS")
print("-" * 60)

negative = (
    hcup_clean["mental_health_admissions"] < 0
).sum()

print(f"Negative values: {negative}")

# distribution

print("\n6. DISTRIBUTION")
print("-" * 60)

print(
    hcup_clean["mental_health_admissions"]
    .describe()
)

# national annual totals

print("\n7. NATIONAL TOTALS")
print("-" * 60)

national = (
    hcup_clean
    .groupby("Year")["mental_health_admissions"]
    .sum()
    .reset_index()
)

print(national)

# largest state-years

print("\n8. TOP 20 STATE-YEAR TOTALS")
print("-" * 60)

display(
    hcup_clean
    .sort_values(
        "mental_health_admissions",
        ascending=False
    )
    .head(20)
)

# manual verification helper

print("\n9. MANUAL HCUP CROSS-CHECK")
print("-" * 60)

state = input("Enter State (example: California): ").strip()
year = int(input("Enter Year (2013-2023): "))

quarter_cols = [
    f"{year} Q1",
    f"{year} Q2",
    f"{year} Q3",
    f"{year} Q4"
]

manual = (
    mh[
        mh["State"] == state
    ][
        ["Expected Payer"] + quarter_cols
    ]
    .copy()
)

manual["Annual Total"] = manual[
    quarter_cols
].sum(axis=1)

display(manual)

pipeline_total = hcup_clean.loc[
    (hcup_clean["State"] == state)
    &
    (hcup_clean["Year"] == year),
    "mental_health_admissions"
]

print("\nPipeline annual total:")

if len(pipeline_total):
    print(int(pipeline_total.iloc[0]))
else:
    print("No value found.")

print("\nManual sum of payer totals:")

if len(manual):
    print(int(manual["Annual Total"].sum()))
else:
    print("No HCUP rows found.")

# comparison


print("\n10. COMPARISON RESULT")
print("-" * 60)

if len(pipeline_total) and len(manual):

    difference = (
        int(pipeline_total.iloc[0])
        - int(manual["Annual Total"].sum())
    )

    print(f"Difference = {difference}")

    if difference == 0:
        print("PASS ✓ Pipeline exactly matches HCUP source.")
    else:
        print("FAIL ✗ Values differ. Investigate extraction.")

else:
    print("Comparison could not be completed.")

============================================================
HCUP ACCURACY AUDIT
============================================================

1. CLEAN DATASET SUMMARY
------------------------------------------------------------
Rows: 496
States: 46
Years: [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

2. DUPLICATE STATE-YEAR CHECK
------------------------------------------------------------
Duplicate State-Year rows: 0

3. MISSING STATE-YEAR COMBINATIONS
------------------------------------------------------------
Missing combinations: 10
          State  Year
0        Alaska  2013
1        Alaska  2014
43   California  2023
55     Delaware  2013
56     Delaware  2014
57     Delaware  2015
272      Nevada  2021
273      Nevada  2022
274      Nevada  2023
450     Vermont  2023

4. MISSING VALUES
------------------------------------------------------------
State                       0
Year                        0
mental_health_admissions    0
dtype: int64

5. NEGATIVE ADMISSIONS
------------------------------------------------------------
Negative values: 0

6. DISTRIBUTION
------------------------------------------------------------
count       496.000000
mean      27206.250000
std       29563.800402
min        1150.000000
25%        8287.500000
50%       16175.000000
75%       33712.500000
max      145100.000000
Name: mental_health_admissions, dtype: float64

7. NATIONAL TOTALS
------------------------------------------------------------
    Year  mental_health_admissions
0   2013                 1307900.0
1   2014                 1342000.0
2   2015                 1333550.0
3   2016                 1233950.0
4   2017                 1260900.0
5   2018                 1276750.0
6   2019                 1258550.0
7   2020                 1155950.0
8   2021                 1155900.0
9   2022                 1117550.0
10  2023                 1051300.0

8. TOP 20 STATE-YEAR TOTALS
------------------------------------------------------------

          State  Year  mental_health_admissions
73     New York  2014                  145100.0
119    New York  2015                  144950.0
27     New York  2013                  144900.0
257    New York  2018                  141700.0
303    New York  2019                  139350.0
211    New York  2017                  139200.0
165    New York  2016                  137600.0
49   California  2014                  124900.0
95   California  2015                  121600.0
233  California  2018                  121450.0
3    California  2013                  120850.0
349    New York  2020                  120000.0
279  California  2019                  118350.0
187  California  2017                  116000.0
487    New York  2023                  114550.0
141  California  2016                  113750.0
441    New York  2022                  112400.0
98      Florida  2015                  111700.0
395    New York  2021                  110200.0
371  California  2021                  109900.0

9. MANUAL HCUP CROSS-CHECK
------------------------------------------------------------

Enter State (example: California):  arizona
Enter Year (2013-2023):  2015

Empty DataFrame
Columns: [Expected Payer, 2015 Q1, 2015 Q2, 2015 Q3, 2015 Q4, Annual Total]
Index: []

Pipeline annual total:
No value found.

Manual sum of payer totals:
No HCUP rows found.

10. COMPARISON RESULT
------------------------------------------------------------
Comparison could not be completed.

In [19]:

# Dataset Schema Validation and Merge Preparation
#Inspect source datasets before building the final
# state-year analytical panel.

# Sources:
#  Google Trends search activity
#  HCUP inpatient admissions data
# U.S. Census population estimates


import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 250)
pd.set_option("display.max_colwidth", 100)

# project directory

RAW = Path(
    "/Users/caseybrookshier/Desktop/Data Science job attainment planning/"
    "DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"
)

GT_FILE = RAW / "google_trends_raw_progress.csv"
HCUP_FILE = RAW / "DownloadTable_StatePayerIP_2026-03-20.xls"
CENSUS_FILE = RAW / "uscb_state_population_2013_2023.csv"

# dataset inspection function

def inspect(df, name):

    print("\n")
    print("=" * 100)
    print(name.upper())
    print("=" * 100)

    print("\nShape")
    print(df.shape)

    print("\nColumns")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nFirst 20 Rows")
    print(df.head(20))

    print("\nLast 10 Rows")
    print(df.tail(10))

    print("\nMissing Values")
    print(df.isna().sum())

    print("\nUnique Values")
    print(df.nunique())

    print("\nCandidate Merge Columns")

    for col in df.columns:

        check = col.lower()

        if any(
            term in check
            for term in [
                "state",
                "year",
                "quarter",
                "month",
                "date",
                "region"
            ]
        ):

            print(f"\n{col}")

            try:
                print(
                    df[col]
                    .drop_duplicates()
                    .head(20)
                    .tolist()
                )
            except Exception:
                pass

# Google Trends dataset

google = pd.read_csv(
    GT_FILE
)

inspect(
    google,
    "Google Trends"
)

# HCUP dataset

print("\n")
print("=" * 100)
print("HCUP WORKBOOK")
print("=" * 100)


xls = pd.ExcelFile(
    HCUP_FILE
)

print("\nAvailable Sheets")
print(xls.sheet_names)


hcup = pd.read_excel(
    HCUP_FILE
)

inspect(
    hcup,
    "HCUP"
)

# census population dataset

census = pd.read_csv(
    CENSUS_FILE
)

inspect(
    census,
    "U.S. Census Population"
)

# schema comparison

print("\n")
print("=" * 100)
print("COMMON COLUMN NAMES")
print("=" * 100)


common_columns = (
    set(google.columns)
    &
    set(hcup.columns)
    &
    set(census.columns)
)

print(
    sorted(common_columns)
)


print("\n")
print("=" * 100)
print("DATASET VALIDATION COMPLETE")
print("=" * 100)


print(
"""
Inspection complete.
"""
)

====================================================================================================
GOOGLE TRENDS
====================================================================================================

Shape
(4411, 11)

Columns
['Year', 'suicidal thoughts', 'State', 'Search_Term', 'suicide hotline', 'self harm', 'mental health crisis', 'suicide prevention', 'crisis hotline', 'psychiatric hospital', 'depression help']

Data Types
Year                      int64
suicidal thoughts       float64
State                    object
Search_Term              object
suicide hotline         float64
self harm               float64
mental health crisis    float64
suicide prevention      float64
crisis hotline          float64
psychiatric hospital    float64
depression help         float64
dtype: object

First 20 Rows
    Year  suicidal thoughts    State        Search_Term  suicide hotline  self harm  mental health crisis  suicide prevention  crisis hotline  psychiatric hospital  depression help
0   2013          66.833333  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
1   2014          42.083333  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
2   2015          47.250000  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
3   2016          52.250000  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
4   2017          50.833333  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
5   2018          65.000000  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
6   2019          59.666667  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
7   2020          42.250000  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
8   2021          31.000000  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
9   2022          45.666667  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
10  2023          41.333333  Alabama  suicidal thoughts              NaN        NaN                   NaN                 NaN             NaN                   NaN              NaN
11  2013                NaN  Alabama    suicide hotline        11.166667        NaN                   NaN                 NaN             NaN                   NaN              NaN
12  2014                NaN  Alabama    suicide hotline        14.500000        NaN                   NaN                 NaN             NaN                   NaN              NaN
13  2015                NaN  Alabama    suicide hotline        33.916667        NaN                   NaN                 NaN             NaN                   NaN              NaN
14  2016                NaN  Alabama    suicide hotline        38.583333        NaN                   NaN                 NaN             NaN                   NaN              NaN
15  2017                NaN  Alabama    suicide hotline        61.166667        NaN                   NaN                 NaN             NaN                   NaN              NaN
16  2018                NaN  Alabama    suicide hotline        68.000000        NaN                   NaN                 NaN             NaN                   NaN              NaN
17  2019                NaN  Alabama    suicide hotline        54.500000        NaN                   NaN                 NaN             NaN                   NaN              NaN
18  2020                NaN  Alabama    suicide hotline        55.083333        NaN                   NaN                 NaN             NaN                   NaN              NaN
19  2021                NaN  Alabama    suicide hotline        49.666667        NaN                   NaN                 NaN             NaN                   NaN              NaN

Last 10 Rows
      Year  suicidal thoughts                 State      Search_Term  suicide hotline  self harm  mental health crisis  suicide prevention  crisis hotline  psychiatric hospital  depression help
4401  2014                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        17.250000
4402  2015                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        37.416667
4403  2016                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        35.750000
4404  2017                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        33.416667
4405  2018                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN         9.916667
4406  2019                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        17.416667
4407  2020                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        19.833333
4408  2021                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN         5.250000
4409  2022                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        10.083333
4410  2023                NaN  District of Columbia  depression help              NaN        NaN                   NaN                 NaN             NaN                   NaN        11.083333

Missing Values
Year                       0
suicidal thoughts       3861
State                      0
Search_Term                0
suicide hotline         3850
self harm               3850
mental health crisis    3872
suicide prevention      3850
crisis hotline          3883
psychiatric hospital    3861
depression help         3850
dtype: int64

Unique Values
Year                     11
suicidal thoughts       344
State                    51
Search_Term               8
suicide hotline         368
self harm               398
mental health crisis    271
suicide prevention      302
crisis hotline          278
psychiatric hospital    356
depression help         366
dtype: int64

Candidate Merge Columns

Year
[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

State
['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland']


====================================================================================================
HCUP WORKBOOK
====================================================================================================

Available Sheets
['About This File', 'Data Notes & Methods', 'Data', 'ICD-10-CM Definition Changes', 'Asthma Data', 'CHF Data', 'Diabetes Data']


====================================================================================================
HCUP
====================================================================================================

Shape
(15, 1)

Columns
['About This File']

Data Types
About This File    object
dtype: object

First 20 Rows
                                                                                        About This File
0   This file was exported from HCUP Fast Stats, State Trends in Inpatient Stays by Payer (https://d...
1   The Data Notes & Methods worksheet contains the same data notes and methods viewed on the HCUP F...
2   The Data worksheet reports the number of inpatient stays for every available calendar quarter at...
3   The ICD-10-CM Definition Changes worksheet reports the average percentage of change, across Stat...
4   The Asthma Data worksheet includes historical data previously reported in HCUP Fast Stats for as...
5   The CHF Data worksheet includes historical data previously reported in HCUP Fast Stats for conge...
6   The Diabetes Data worksheet includes historical data previously reported in HCUP Fast Stats for ...
7                         Available States are participating in both HCUP and the HCUP Fast Stats tool.
8   Quarterly counts have been rounded up to the nearest 50 inpatient stays. If a cell in the Data w...
9         This file includes all back year data, not all of which will be displayed in HCUP Fast Stats.
10  In using these data please read Requirements for Publishing with HCUP Data (https://hcup-us.ahrq...
11  Suggested Citation: HCUP Fast Stats, State Trends by Payer for Adult Inpatient Stays, Healthcare...
12                                                                                                  NaN
13                                                                  Reflects HCUP data as of 3/20/2026.
14                                                                   Excel file last updated 4/21/2026.

Last 10 Rows
                                                                                        About This File
5   The CHF Data worksheet includes historical data previously reported in HCUP Fast Stats for conge...
6   The Diabetes Data worksheet includes historical data previously reported in HCUP Fast Stats for ...
7                         Available States are participating in both HCUP and the HCUP Fast Stats tool.
8   Quarterly counts have been rounded up to the nearest 50 inpatient stays. If a cell in the Data w...
9         This file includes all back year data, not all of which will be displayed in HCUP Fast Stats.
10  In using these data please read Requirements for Publishing with HCUP Data (https://hcup-us.ahrq...
11  Suggested Citation: HCUP Fast Stats, State Trends by Payer for Adult Inpatient Stays, Healthcare...
12                                                                                                  NaN
13                                                                  Reflects HCUP data as of 3/20/2026.
14                                                                   Excel file last updated 4/21/2026.

Missing Values
About This File    1
dtype: int64

Unique Values
About This File    14
dtype: int64

Candidate Merge Columns


====================================================================================================
U.S. CENSUS POPULATION
====================================================================================================

Shape
(638, 3)

Columns
['State', 'Year', 'state_population']

Data Types
State                object
Year                  int64
state_population    float64
dtype: object

First 20 Rows
      State  Year  state_population
0   Alabama  2013         4831586.0
1   Alabama  2014         4843737.0
2   Alabama  2015         4854803.0
3   Alabama  2016         4866824.0
4   Alabama  2017         4877989.0
5   Alabama  2018         4891628.0
6   Alabama  2019         4907965.0
7   Alabama  2020         4921532.0
8   Alabama  2021         5050058.0
9   Alabama  2022         5076868.0
10  Alabama  2023         5117850.0
11   Alaska  2013          737626.0
12   Alaska  2014          737075.0
13   Alaska  2015          738430.0
14   Alaska  2016          742575.0
15   Alaska  2017          740983.0
16   Alaska  2018          736624.0
17   Alaska  2019          733603.0
18   Alaska  2020          731158.0
19   Alaska  2021          734590.0

Last 10 Rows
    State  Year  state_population
628   NaN  2014               NaN
629   NaN  2015               NaN
630   NaN  2016               NaN
631   NaN  2017               NaN
632   NaN  2018               NaN
633   NaN  2019               NaN
634   NaN  2020               NaN
635   NaN  2021               NaN
636   NaN  2022               NaN
637   NaN  2023               NaN

Missing Values
State               11
Year                 0
state_population    77
dtype: int64

Unique Values
State                57
Year                 11
state_population    561
dtype: int64

Candidate Merge Columns

State
['Alabama', 'Alaska', 'Annual Estimates of the Resident Population for the United States, Regions, States, the District of Columbia, and Puerto Rico: April 1, 2010 to July 1, 2019; April 1, 2020; and July 1, 2020 (NST-EST2020)', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'In May 2021, the estimates for Puerto Rico Commonwealth were appended to this file  In July 2021, estimates as of April 1, 2020 were appended to this file  No changes were made to the data originally released in December 2020', 'Indiana', 'Iowa', 'Kansas', 'Kentucky']

Year
[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

state_population
[4831586.0, 4843737.0, 4854803.0, 4866824.0, 4877989.0, 4891628.0, 4907965.0, 4921532.0, 5050058.0, 5076868.0, 5117850.0, 737626.0, 737075.0, 738430.0, 742575.0, 740983.0, 736624.0, 733603.0, 731158.0, 734590.0]


====================================================================================================
COMMON COLUMN NAMES
====================================================================================================
[]


====================================================================================================
DATASET VALIDATION COMPLETE
====================================================================================================

Inspection complete.

In [18]:
# TEAM RHO FINAL MERGE PIPELINE

# Inputs:
#  google_trends_raw_progress.csv
#  hcup_state_year_mental_health_admissions_2013_2023.csv
#  uscb_state_population_2013_2023.csv

# Output: team_rho_state_year_prediction_dataset.csv


import pandas as pd
from pathlib import Path

# Paths

RAW = Path(
    "/Users/caseybrookshier/Desktop/Data Science job attainment planning/"
    "DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw"
)

GT_FILE = RAW / "google_trends_raw_progress.csv"

HCUP_FILE = RAW / (
    "hcup_state_year_mental_health_admissions_2013_2023.csv"
)

CENSUS_FILE = RAW / (
    "uscb_state_population_2013_2023.csv"
)

OUTPUT = RAW / (
    "team_rho_state_year_prediction_dataset.csv"
)

# GOOGLE TRENDS

google = pd.read_csv(GT_FILE)

google["State"] = google["State"].astype(str).str.strip()
google["Year"] = google["Year"].astype(int)

search_terms = [
    "suicidal thoughts",
    "suicide hotline",
    "self harm",
    "mental health crisis",
    "suicide prevention",
    "crisis hotline",
    "psychiatric hospital",
    "depression help"
]

for term in search_terms:
    google[term] = pd.to_numeric(
        google[term],
        errors="coerce"
    ).fillna(0)

google_year = (
    google
    .groupby(["State", "Year"], as_index=False)[search_terms]
    .sum()
)

# HCUP


hcup = pd.read_csv(HCUP_FILE)

hcup["State"] = hcup["State"].astype(str).str.strip()
hcup["Year"] = hcup["Year"].astype(int)

print("\nHCUP columns:")
print(hcup.columns.tolist())

required = [
    "State",
    "Year",
    "mental_health_admissions"
]

missing = [
    c for c in required
    if c not in hcup.columns
]

if missing:
    raise ValueError(
        f"HCUP file missing required columns: {missing}"
    )

# CENSUS

census = pd.read_csv(CENSUS_FILE)

census = census[
    census["State"].notna()
].copy()

census = census[
    census["state_population"].notna()
]

census["State"] = (
    census["State"]
    .astype(str)
    .str.strip()
)

census["Year"] = (
    census["Year"]
    .astype(int)
)

census = census[
    census["Year"].between(2013, 2023)
]

#MERGE

dataset = (
    google_year
    .merge(
        hcup,
        on=["State", "Year"],
        how="inner"
    )
    .merge(
        census,
        on=["State", "Year"],
        how="inner"
    )
)

print("\nMerged shape:")
print(dataset.shape)



# REMOVE HCUP MISSING VALUES

# note HCUP zeros represent unavailable reporting.

dataset = dataset[
    dataset["mental_health_admissions"] > 0
].copy()

#  ADMISSION RATE

dataset["admission_rate_per_100k"] = (
    dataset["mental_health_admissions"]
    /
    dataset["state_population"]
    * 100000
)

# CREATE LAGGED GOOGLE VARIABLES

dataset = dataset.sort_values(
    ["State", "Year"]
)

for term in search_terms:

    dataset[f"{term}_lag1"] = (
        dataset
        .groupby("State")[term]
        .shift(1)
    )

dataset = dataset[
    dataset["Year"] >= 2014
].copy()


#  KEEP MODEL VARIABLES


final_columns = [
    "State",
    "Year",
    "state_population",
    "mental_health_admissions",
    "admission_rate_per_100k"
]

final_columns.extend(
    [
        f"{term}_lag1"
        for term in search_terms
    ]
)

dataset = dataset[
    final_columns
]

# FINAL VALIDATION

print("\n" + "=" * 70)
print("TEAM RHO FINAL DATASET")
print("=" * 70)

print("\nShape:")
print(dataset.shape)

print("\nStates:")
print(dataset["State"].nunique())

print("\nYears:")
print(sorted(dataset["Year"].unique()))

print("\nDuplicate State-Year rows:")
print(
    dataset.duplicated(
        ["State", "Year"]
    ).sum()
)

print("\nMissing values:")
print(dataset.isna().sum())

print("\nAdmission rate summary:")
print(
    dataset["admission_rate_per_100k"]
    .describe()
)

print("\nOutcome summary:")
print(
    dataset["mental_health_admissions"]
    .describe()
)

print("\nFirst 20 rows:")
display(
    dataset.head(20)
)

# SAVE

dataset.to_csv(
    OUTPUT,
    index=False
)

print("\nSaved to:")
print(OUTPUT)

HCUP columns:
['State', 'Year', 'mental_health_admissions']

Merged shape:
(496, 12)

======================================================================
TEAM RHO FINAL DATASET
======================================================================

Shape:
(452, 13)

States:
46

Years:
[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

Duplicate State-Year rows:
0

Missing values:
State                        0
Year                         0
state_population             0
mental_health_admissions     0
admission_rate_per_100k      0
suicidal thoughts_lag1       2
suicide hotline_lag1         2
self harm_lag1               2
mental health crisis_lag1    2
suicide prevention_lag1      2
crisis hotline_lag1          2
psychiatric hospital_lag1    2
depression help_lag1         2
dtype: int64

Admission rate summary:
count    452.000000
mean     401.799501
std      148.153914
min      110.110717
25%      285.128151
50%      395.847518
75%      497.956771
max      826.908647
Name: admission_rate_per_100k, dtype: float64

Outcome summary:
count       452.000000
mean      26961.061947
std       29354.382407
min        1150.000000
25%        8337.500000
50%       16050.000000
75%       33562.500000
max      145100.000000
Name: mental_health_admissions, dtype: float64

First 20 rows:

,State,Year,state_population,mental_health_admissions,admission_rate_per_100k,suicidal thoughts_lag1,suicide hotline_lag1,self harm_lag1,mental health crisis_lag1,suicide prevention_lag1,crisis hotline_lag1,psychiatric hospital_lag1,depression help_lag1
0,Alaska,2015,738430.0,2200.0,297.929391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,2016,742575.0,2150.0,289.533044,0.000000,0.000000,16.000000,0.000000,9.250000,0.000000,0.000000,0.000000
2,Alaska,2017,740983.0,2250.0,303.650691,0.000000,0.000000,6.333333,0.000000,12.750000,0.000000,0.000000,13.250000
3,Alaska,2018,736624.0,2350.0,319.023002,7.666667,24.333333,7.500000,0.000000,3.666667,0.000000,0.000000,6.416667
4,Alaska,2019,733603.0,2450.0,333.968100,0.000000,22.000000,0.000000,0.000000,18.333333,0.000000,8.333333,5.583333
5,Alaska,2020,731158.0,2550.0,348.761827,0.000000,11.416667,0.000000,0.000000,27.500000,0.000000,0.000000,10.583333
6,Alaska,2021,734590.0,2800.0,381.165004,0.000000,14.500000,0.000000,0.000000,11.916667,0.000000,0.000000,8.333333
7,Alaska,2022,733659.0,2900.0,395.279006,0.000000,7.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000
8,Alaska,2023,734654.0,2750.0,374.325873,0.000000,15.333333,15.916667,0.000000,11.500000,0.000000,0.000000,3.750000
10,Arizona,2014,6732873.0,15050.0,223.530133,67.750000,26.416667,69.833333,4.833333,21.083333,6.333333,50.083333,53.416667
11,Arizona,2015,6832810.0,14300.0,209.284321,78.333333,28.750000,78.583333,8.583333,23.666667,22.833333,44.666667,59.000000
12,Arizona,2016,6944767.0,14300.0,205.910436,68.666667,26.500000,70.333333,0.000000,28.250000,36.083333,50.083333,64.333333
13,Arizona,2017,7048088.0,13850.0,196.507195,66.750000,34.000000,49.583333,12.750000,22.583333,55.083333,49.416667,63.750000
14,Arizona,2018,7164228.0,17500.0,244.269166,64.416667,57.083333,51.250000,17.750000,29.750000,58.583333,51.166667,67.750000
15,Arizona,2019,7291843.0,16050.0,220.108963,70.333333,57.500000,47.750000,22.416667,35.416667,66.333333,57.000000,74.250000
16,Arizona,2020,7421401.0,16200.0,218.287625,64.000000,47.416667,41.833333,31.916667,37.916667,70.750000,55.250000,73.083333
17,Arizona,2021,7274022.0,15950.0,219.273464,48.833333,44.500000,44.250000,45.916667,31.750000,57.333333,52.500000,72.500000
18,Arizona,2022,7370065.0,12100.0,164.177657,52.250000,44.416667,54.166667,45.000000,31.833333,73.083333,67.500000,77.083333
19,Arizona,2023,7452073.0,20450.0,274.420285,44.333333,53.916667,49.750000,65.666667,35.833333,67.333333,70.666667,79.750000
21,Arkansas,2014,2968759.0,15300.0,515.366859,19.833333,6.166667,53.666667,0.000000,23.250000,0.000000,9.166667,25.000000

Saved to:
/Users/caseybrookshier/Desktop/Data Science job attainment planning/DS Portfolio github friendly/Team-Rho-Capstone-Project.cb/data/raw/team_rho_state_year_prediction_dataset.csv